name: "ROS2 Test Action"
description: "Runs Greenroom's standard ROS2 test setup"
author: "Greenroom Robotics"
branding:
  icon: "package"
  color: "gray-dark"
inputs:
  token:
    description: "The Github token with access to the packages repo and release api"
    required: true
  ros_distro:
    description: "The ROS2 distro to use"
    required: false
  gpu:
    description: "Whether to build with GPU support (true/false)"
    required: false
    default: "false"
  tests:
    description: "Whether to run tests (true/false)"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Checkout this repository
      uses: actions/checkout@v6
      with:
        lfs: true

    # Added after flakiness notes on self-hosted runners (runs-on).
    # More details in: https://github.com/actions/checkout/issues/270
    - name: Fetching LFS Data
      shell: bash
      run: |
        git lfs pull --exclude=""

    # - name: Collect Workflow Telemetry
    #   uses: Greenroom-Robotics/workflow-telemetry-action@main

    - name: Build Docker Container
      shell: bash
      env:
        API_TOKEN_GITHUB: ${{ inputs.token }}
        GPU: ${{ inputs.gpu }}
        ROS_DISTRO: ${{ inputs.ros_distro }}
      run: docker compose build

    - name: Run Tests
      if: ${{ inputs.tests == 'true' }}
      shell: bash
      env:
        API_TOKEN_GITHUB: ${{ inputs.token }}
        GPU: ${{ inputs.gpu }}
        ROS_DISTRO: ${{ inputs.ros_distro }}
      run: |
        mkdir results && chmod a+w results
        docker compose run tests

    - name: Publish Test Report
      uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 #v3
      if: ${{ always() && inputs.tests == 'true' && hashFiles('results/**/*.xml') != '' }}
      with:
        name: Test Report
        path: 'results/**/*.xml'
        reporter: java-junit
        fail-on-error: false
