name: "ROS2 Test Action"
description: "Runs Greenroom's standard ROS2 test setup"
author: "Greenroom Robotics"
branding:
  icon: "package"
  color: "gray-dark"
inputs:
  token:
    description: "The Github token with access to the packages repo and release api"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

#     - name: Collect Workflow Telemetry
#       uses: Greenroom-Robotics/workflow-telemetry-action@main

    - name: Build Docker Container
      shell: bash
      env:
        API_TOKEN_GITHUB: ${{ inputs.token }}
      run: docker compose build

    - name: Run Tests
      shell: bash
      env:
        API_TOKEN_GITHUB: ${{ inputs.token }}
      run: |
        mkdir results && chmod a+w results
        docker compose run tests

    - name: Publish Test Report
      uses: Greenroom-Robotics/action-junit-report@main
      if: always() # always run even if the previous step fails
      with:
        check_name: 'Test Report'
        report_paths: 'results/*/*.xml'
