name: "ROS Test Action"
description: "Runs Greenroom's standard ros test setup"
author: "Greenroom Robotics"
branding:
  icon: "package"
  color: "gray-dark"
inputs:
  token:
    description: "The Github token with access to the packages repo and release api"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Build Docker Container
      env:
        API_TOKEN_GITHUB: ${{ inputs.token }}
      shell: bash
      run: docker compose build

    - name: Run tests
      shell: bash
      env:
        API_TOKEN_GITHUB: ${{ inputs.token }}
      run: docker compose run tests
